base:
  db: mongodb://localhost/reversi-portal
  redis: redis://localhost
  secret: your_secret
  port: 8888
  host: 127.0.0.1:8888
  cspReportUrl: /
  urlPrefix: ''
  cdnPrefix: ''
  scoreboard:
    cacheDuration: 600000     # 10 minutes
  web:
    realtimePush: true        # disable realtime push if you have many judgers
  api:
    credential:
      username: foo
      password: bar
  compile:
    display:
      gcc51c11:     TDM-GCC 5.1.0 (Release, 32-bit, with C11)
      gcc49c11:     TDM-GCC 4.9.2 (Release, 32-bit, with C11)
      msvc2017:     Visual C++ 2017 (Release, x86)
      llvm40:       LLVM 4.0 (Xcode 9.0, i386)
    limits:
      sizeOfCode: 1048576     # 1 MB
      sizeOfBin: 1048576      # 1 MB
      sizeOfText: 102400      # 100 KB
      submitInterval: 300000  # 5 minutes, for students
      minSubmitInterval: 60000 # 1 minute, for administrators
      maxExecQuota: 36000000  # 10 hours
  match:
    rules:
      moveTimeout: 1000       # 5 s
      roundTimeout: 180000    # 180 s
      memoryLimit: 367001600  # 350 MB
      size: 16
      roundLlimit: 120
  profiling:
    eventBus: false
    addMatches: false
  mq:
    vhosts:
      /:
        connection:
          hostname: localhost
          user: guest
          password: guest
        queues:
          - reversi_compile
          - reversi_judge
        publications:
          compile:
            queue: reversi_compile
          judge:
            queue: reversi_judge
