base:
  redis: 
    host: localhost
    port: 6379
    password: redis
  db: mongodb://makyek:makyek@localhost:27017/db
  secret: arbitrary-secret
  port: 8888
  host: localhost
  cspReportUrl: /
  urlPrefix: ''
  cdnPrefix: ''
  scoreboard:
    cacheDuration: 600000     # 10 minutes
  web:
    realtimePush: true        # disable realtime push if you have many judgers
  api:
    credential:
      username: foo
      password: bar
  compile:
    display:
      gcc51c11:     TDM-GCC 5.1.0 (Release, 64-bit, with C11)
    limits:
      sizeOfCode: 1048576     # 1 MB
      sizeOfBin: 1048576      # 1 MB
      sizeOfText: 102400      # 100 KB
      submitInterval: 300000  # 5 minutes, for students
      minSubmitInterval: 60000 # 1 minute, for administrators
      maxExecQuota: 36000000  # 10 hours
  match:
    rules:
      moveTimeout: 2000       # 2 s
      roundTimeout: 90000    # 90 s
      memoryLimit: 367001600  # 350 MB
      size: 12
      roundLlimit: 60
  profiling:
    eventBus: false
    addMatches: false
  mq:
    vhosts:
      /:
        connection:
          hostname: localhost
          user: root
          password: 123456
        queues:
          - reversi_compile
          - reversi_judge
        publications:
          compile:
            queue: reversi_compile
          judge:
            queue: reversi_judge
